### ISSUE TITLE
Configuração do .htaccess

### ISSUE THREAD

**Issue by carvalhobruno** [pokemongovet/pokemongo.vet.br#15]
Não sei se hoje é possivel fazer, mas fica como pendência:

- [ ] Remover o .html do site

- [ ] Implantar compatação GZIP

**Comment by fititnt** [comment]
No momento, estamos usando o Github Pages https://pages.github.com/, e tenho quase certeza que ele não deve aceitar isso.

 Esse issue está relacionado com o #12. Vou deixar ele aberto e ver feedback do pessoal. Mesmo que ele seja fechado, a tendência, se o o projeto crescer, é ele ser implementado no futuro. Talvez esse seu PR faça a gente criar uma tag "bloqueado" pra ficar mais claro pras pessoas

**Comment by fabricionaweb** [comment]
Sugestão: [surge.sh](https://surge.sh)

É uma hospedagem grátis, estática, super simples de dar deploy. Tem urls amigáveis, aceita pushState (caso futuramente seja necessário), tem página 404, aceita CNAME, mapa de rotas, regex, entre diversas boas features. 🤘

Fiz um pequeno [post](http://fabricionaweb.me/post/hospedando-sites-estaticos-gratuitamente) sobre isso, mas a [documentação](https://surge.sh/help/) é suficientemente boa.

É possivel estudar um deploy automático depois de passar por alguns testes de lint, usando [travis.ci](https://travis-ci.org/) ou apenas deixar por conta do administrador fazer os deploys...

Abraços

**Comment by fititnt** [comment]
Pessoal, vou fechar, provavelmente temporariamente, conforme descrito nesse comentário aqui https://github.com/pokemongovet/pokemongo.vet.br/pull/45#issuecomment-237100473.

E as opiniões do @fabricionaweb foram perfeitas pra explicar como implementar como reabrir o issue, mas isso precisa, no mínimo, de um período de transição, sendo que no momento vale mais a pena focar no #48 #49 e #50.
