### ISSUE TITLE
Página de listagem dos centros cadastrados

### ISSUE THREAD

**Issue by cauequeiroz** [pokemongovet/pokemongo.vet.br#21]
Hey folks!

Precisamos pensar em uma forma bem bacana de exibir as informações que ja foram cadastradas. Acabei de mandar um PR com uma sugestão de como poderia ser feito isso.

Como disse por lá, pensei em fazer algo bem limpo e organizado, com a navegação no topo idealizada pelo @fititnt e todos os estados e locais estruturados.

- Para estados que não tem nada cadastrado, deixei uma mensagem com link para o usuario cadastrar.
- Para estados que tem algo cadastrados, sugiro seguir esse padrão, não importando se é local de adoção, grupo do facebook ou ong.

Obs: nesse PR estou enviando a estrutura generica codificada e estilizada. Caso isso seja aprovado, vou ajudar em outros PR's a popular com o que ja temos nessa nova estrutura.

Seria bacana tentar padronizar como os dados serão exibidos, porque ai não importa se terão 2 ou 200 centros cadastrados, tudo vai seguir o mesmo padrão visual.

Segue algumas imagens do que eu pensei:

![pokemon_01](https://cloud.githubusercontent.com/assets/8504348/17271150/09c5e116-564b-11e6-94f3-5df46cebb157.png)
![pokemon_02](https://cloud.githubusercontent.com/assets/8504348/17271149/09c1d90e-564b-11e6-8706-17f10c6e0544.png)
![pokemon_03](https://cloud.githubusercontent.com/assets/8504348/17271151/09cbbf3c-564b-11e6-9905-7682045e15bd.png)

**Comment by fititnt** [comment]
Por mim o novo layout está ok, porém o PR #24, nesse momento, não está pronto para merge. Já conversei com o Caue

**Comment by alvarengathomas** [comment]
Não seria melhor fazer algo com google maps?
Colocando um campo para pesquisa de endereço e marcando os centros pokemon como pontos de interesse?

**Comment by cauequeiroz** [comment]
@alvarengathomas É uma opção bem bacana cara! haha

@icoffani @rcgivisiez o que acharam desse novo layout para pagina de listagem?

**Comment by icoffani** [comment]
@cauequeiroz achei muito bacana! Mais limpo e mais organizado do que o atual. Considero o Google Maps algo a se discutir e de se acrescentar depois se for conveniente, pode até criar um novo issue sobre para ampliar a discussão.

**Comment by alvarengathomas** [comment]
@icoffani vou criar a issue de Google maps

**Comment by fititnt** [comment]
Eita, tava revendo os issues e vi esse topico aqui agora.

![respondi mentalmente](http://perolasdowhatsapp.com.br/wp-content/uploads/2015/11/imagens-engracadas-whatsapp-eu-leio-a-mensagem-respondo-ela-mentalmente-e-esqueco-de-responder-de-verdade-mas-no-meu-coracao-eu-respondi-e-e-isso-que-importa.jpg)

Eu tinha colocado bloqueado pra evitar que a Isa e a Re aceitassem o PR e quebrar o site, mas esqueci de fechar ou de avisar elas que agora tava ok.

Se em outro momento vocês verem por aqui algo que já estava pronto, mas foi esquecido aberto podem dar um bump avisando
