### ISSUE TITLE
Inclusão de arquivo .editorconfig

### ISSUE THREAD

**Issue by woliveiras** [pokemongovet/pokemongo.vet.br#30]
Com a entrada de novos contribuidores, pode ser interessante colocar uma padronização no código fonte do projeto.

Um arquivo .editorconfig pode ajudar nisso.

Mais informações sobre o .editorconfig: http://editorconfig.org/

Ex. de arquivo: https://github.com/woliveiras/kibe/blob/master/.editorconfig

**Comment by fititnt** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0

**Comment by woliveiras** [comment]
UHAUHAUHAHUAUHAUHUH

Demorou @fititnt

**Comment by evansantos** [comment]
@woliveiras já foi feito pelo @welksonramos na issue #5, está em PR

**Comment by evansantos** [comment]
@fititnt fecha essa issue, por favor 😉

**Comment by woliveiras** [comment]
Tá lá mano. :smile:
