### ISSUE TITLE
METAS: Quantidade de centros pokemon (opções de adoção)

### ISSUE THREAD

**Issue by icoffani** [pokemongovet/pokemongo.vet.br#36]
Já cumprimos nossas primeiras metas acerca do número mínimo de opções de locais para adoção graças a vocês, pessoal! (vide #10)
Não podemos parar, por isso estabelecemos mais duas metas a serem cumpridas.

- [x] Ter 200 ou mais centros pokemon (opções para adoção).

- [x] Ter 20 ou mais estados do Brasil com pelo menos uma opção para adoção.

## Passo-a-passo fácil para achar os centros para adoção
OBS.: **NÃO** pode adicionar locais de adoção que **permitam a venda de animais**.

**1º**: procurar no [Facebook] (https://www.facebook.com/search/top/?q=&init=mag_glass&tas=0.8788115193205529&search_first_focus=1470009889900) "adoção + cidade de vocês", como na imagem exemplificada a seguir:

![ex](https://cloud.githubusercontent.com/assets/20593469/17280305/3942d3c2-5763-11e6-9259-7ab920ea3b63.jpg)

**2º**: copie os links da pesquisa realizada no Facebook.

**3º**: faça commit [aqui] (https://github.com/pokemongovet/pokemongo.vet.br/pulls) no github.

**4º**: pronto! :)

**Eu não sei fazer código, e agora?**
Caso você não seja programador mas quer nos ajudar pode avisar aqui ou entrar em contato por e-mail que nós conseguimos alguém que faça isso. 

**Exemplos modelo:**
[Adicionado Minas/Uberlândia | APA e Grupo de adoção ] (https://github.com/pokemongovet/pokemongo.vet.br/pull/25)

[Adicionado Goiânia/Goiás - ONGs, Grupos e Instagram] (https://github.com/pokemongovet/pokemongo.vet.br/pull/26)

**Comment by rcgivisiez** [comment]
Isso aqui é importante. Seria uma boa a gente convencer mais gente a responder os locais para adoção pelo menos para cidade aonde moram pra ajudar aqui.

**Comment by rcgivisiez** [comment]
Isso aqui é importante. Seria uma boa a gente convencer mais gente a responder os locais para adoção pelo menos para cidade aonde moram pra ajudar aqui.

Será que pessoal mais experiente está deixando de contribuir com pelo menos uma cidade pra deixar espaço para outros terem cidades diferentes? Se sim, acho que não precisam se preocupar com isso, porque temos milhares de opções pra adotar no Brasil.

**Comment by Dkmister** [comment]
A meta de 20 estados já está concluída. Com a ultima atualização já temos 164 centros.

**Comment by Dkmister** [comment]
Meta de 200 centros atingida. Temos exatos 201.
Esperando pro Tif fechar.

**Comment by blackmoral** [comment]
As metas foram cumpridas! Obrigado a todos os envolvidos, especialmente @Dkmister pelas ultimas contribuições.
