### ISSUE TITLE
Remover extensão .html das páginas do github

### ISSUE THREAD

**Issue by carvalhobruno** [pokemongovet/pokemongo.vet.br#44]
Hoje todos os links para o site apontam para **[url]**.html

O  próprio github aceita a mesma página sem a extensão, que torna o link mais amigável e menos "amadora".

O que deve ser feito:

Removido o .html de todos os links do site. 

Posso me responsabilizar pela tarefa se for ok enviar o pull request até amanhã cedo.

**Comment by fititnt** [comment]
Isso quebra alguma funcionalidade? Se sim, o retorno de usar isso é melhor do que o prejuízo?

**Comment by carvalhobruno** [comment]
@fititnt Não, ele só torna a url mais amigável.

**Comment by fabricionaweb** [comment]
Eu mesmo não sabia que funcionava assim rsrs Bom saber!

**Comment by fititnt** [comment]
Pessoal, vou fechar isso aqui por duplicar o #15 e, também, porque esse outro issue foi fechado por esse motivo aqui https://github.com/pokemongovet/pokemongo.vet.br/issues/15#issuecomment-237101118
