### ISSUE TITLE
Correções na declaração de idioma, ribbon e posicionamento da logo

### ISSUE THREAD

**Issue by blackmoral** [pokemongovet/pokemongo.vet.br#46]
Boa madrugada,

Correções rápidas:

- Atributo **lang** alterado de **pt** para **pt-br**;
- Adicionada a classe **.forkme** e incluida na imagem da ribbon (bug z-index).
- Alteração do posicionamento da logo nas páginas internas após a correção da ribbon.

**Antes:**
![capture9163](https://cloud.githubusercontent.com/assets/6219312/17317897/82d15126-5858-11e6-91c2-5c64bc4e0d04.png)

**Depois:**
![capture10553](https://cloud.githubusercontent.com/assets/6219312/17317882/637a3b3a-5858-11e6-884e-5f07d8082bd6.png)

Basicamente é isso, já está pronto, mandei o PR.

**Comment by fititnt** [comment]
Bacana! Vamos ver gente pra testar seu PR. Não estou no PC agora

**Comment by rcgivisiez** [comment]
Seu PR foi aceito! Muito obrigada, master pokémon @blackmoral!
