### ISSUE TITLE
Ajuda para rushar um site estático Jekyll

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/pokemongo.vet.br#53]
Pessoal, preciso de ajuda pra rushar um site estático Jekyll em https://github.com/pokemongovet/casos-de-sucesso-na-adocao-de-animais enquanto o #48 não está pronto.

Sem PRs e sem muita discussão, pelo menos uma ou duas pessoas pra ficar em contato direto com a @icoffani e a @rcgivisiez por messeger. Nesse meio tempo tem acesso de escrita direto no repositório.

Quem topar deixa o username do Facebook e, no mínimo, coloca artigos ou resolve umas coisas bobas no template que coloquei lá. Só não ficar quebrando a página final. Ou então me mandem mensagem e adicionem direto em https://www.facebook.com/fititnt

Motivo: não tenho tempo pra fazer isso nessa quarta-feira e pouco tempo nessa quinta-feira, e pode ser que o projeto saia a publico antes disso.

**Comment by carvalhobruno** [comment]
@fititnt quais as melhorias que o Jenkyll traria em relação ao que existe hoje? 'Apenas' o reaproveitamento de boa parte do código (e consequentemente remoção de muita coisa repetida) que existe hoje, ou também adicionar algumas funcionalidades de cms ao projeto?

Honestamente nunca mexi com ele, mas pelo que vi ele parece bem simples de lidar, e se ninguém com mais experiência se candidatar, posso fazer entre essa noite e amanhã.

Ficam dois artigos legais:

[Converting a Static Website To Jekyll](https://css-tricks.com/building-a-jekyll-site-part-1-of-3/) (Inglês)
[Building a static website with Jekyll and GitHub Pages](http://programminghistorian.org/lessons/building-static-sites-with-jekyll-github-pages)
[Servindo sites estáticos com Jekyll](http://tableless.com.br/jekyll-servindo-sites-estaticos/) Tableless

**Comment by evansantos** [comment]
@carvalhobruno @fititnt eu já fiz um projeto em jekyll o [internet.org](https://github.com/evansantos/internet.org) e caso queira saber mais eu indico bastante o curso do @willianjusten [criando sites estaticos com jekyll](http://willianjusten.teachable.com/courses/criando-sites-estaticos-com-jekyll)

**Comment by carvalhobruno** [comment]
@evansantos assistindo , valeu!

**Comment by willianjusten** [comment]
Opa, eu posso ajudar se quiserem, mas eu não entendi...parece que já existe até um jekyll funcionando lá no [pokemongovet](https://pokemongovet.github.io/casos-de-sucesso-na-adocao-de-animais/2016-02-02-adote-um-cachorrinho-enquanto-degusta-um-cafe-em-la/), o que precisariam de ajuda?

**Comment by fititnt** [comment]
@evansantos @carvalhobruno @anabastos e @cdiegosr , deem uma conversa com o @willianjusten aqui.

Tirei o urgente e provavelmente vou fechar esse issue hoje. Acho que no mínimo da pra responder ele em particular pra saber o que estamos fazendo.

**Comment by icoffani** [comment]
Pessoal, temos número mínimo de pessoas para ajudar direto sem passar por Pull Request no repositório. Vou fechar esse issue aqui, ok? Se ainda tiver interesse, pode entrar em contato.
