### ISSUE TITLE
Replicar home em nova página: conceito "alugue um cachorro para passear enquanto joga Pokemon Go"

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/pokemongo.vet.br#54]
Na primeira noite que @icoffani @rcgivisiez e eu rushamos o site, era uma meta ter duas ou mais páginas de entrada, com trocadilhos diferentes, pra cativar pessoas do Facebook a visitarem o site. O site, hoje, está apenas com a página inicial.

## Padrão existente: "Pokemon Go Já está disponivel no brasil VS ...via animais reais"
A página atual, ao ser compartilhada, aparece desta forma

![captura de tela de 2016-08-03 15 02 18](https://cloud.githubusercontent.com/assets/812299/17376304/66b31f9a-598b-11e6-9acc-97c437098d5a.png)

Existem várias formas de cativar as pessoas e era, bem ou mal, era uma que, naquele momento, pareceu interessante. E talvez ainda seja enquanto pokemon go não é lançado (o que na data desta postagem é verdade.

Mas sempre é bom se preparar para o futuro ou ter mais opções

## Página extra: "alugue um cachorro para passear enquanto joga Pokemon Go"

Pelo menos um novo padrão precisa ser criado. Vou dar aqui algumas inspirações

- https://twitter.com/xGogsx/status/755876264242708480 (esse está até no nosso /sobre.html)
- (todo: colocar outras)

O conceito seria o seguinte: adicionar uma página que faça alguma referência para levar cães para passear.

No momento zero, podemos apenas redirecionar para a atual página atual de centros pokemons, que tem todos coletados. Porém podemos ver alguma parceria com ONG específica e ir um pouco além, porém pra isso acho uma boa a gente pedir ajuda com @cdiegosr que está cuidando desse contato

## Como fazer

- Copiar a página /index.html para algo relacionado ao trocadilho. Podemos começar com "/aluguel-de-caes.html"
- Trocar textos. Como é página nova, tanto faz o texto, por enquanto ninguém deve saber dela mesmo
- Se você tiver acesso de escrita sem PRs, pode fazer direto. Se tiver alguém aqui muito inspirado e quiser acesso sem passar por PRs, fale comigo diretamente [no meu Facebook](https://www.facebook.com/fititnt)

O ideal seria termos algo ainda nesta quarta-feira. E, algo bem comum de se ouvir ao desenvolver para startups: **não precisa ser perfeito, só precisa ser**, se você tiver muito orgulho do resultado, é porque perdeu tempo demais para lançar

------
# Texto atualizado

Pessoal, a página está publicada em http://pokemongo.vet.br/aluguel-de-animais.html. Obrigado a todas as pessoas que ajudaram.

## Muito Importante
- [ ] Trocar a imagem que aparece ao compartilhar esta página no Facebook/Twitter. Usar debug em https://developers.facebook.com/tools/debug/. Ideal: Provavelmente uma foto de cães muito felizes levados para passear, tamanho exato 1200x630

## Importante
- [ ] A tabela com os preços não quebra muito feio no Mobile. Hotfixes imediatos e melhorias mais decentes mais tardes são muito bem vindas

## Se alguém tiver como
- [ ] Fazer o botão "adotar" tremer de vez em quando (talvez a cada 13~20 segundos, sem precisar de hover do mouse; (sim, isso chama atenção; sim, é chato, mas converte)
- [ ] Pensar em alguma coisa daquelas toscas mesmo, aonde a pessoa tem apenas 10 minutos para aceitar a venda promocional (adoção). É so pra brincar com as pessoas, como essas páginas exageradas de venda
- [ ] Talvez implementar aqueles popups irritantes de quando a pessoa move o mouse para fora da tela ou quer fechar a janela e dizer "Aproveite nossa promoção AGORA e ganhe (algo)". Isso talvez seja bom só ter o conceito que depois a gente discute

Vale a pena quem for contribuir, ler os comentários que fiz no código fonte para verem as motivações https://github.com/pokemongovet/pokemongo.vet.br/blob/gh-pages/aluguel-de-animais.html#L1

**Comment by blackmoral** [comment]
Achei ótima a ideia para atrair o público com diferentes chamadas. Porém dou minha humilde opinião quanto algunas questões.

**1** - Explorar mais a intenção do projeto, não gerar a curiosidade só no jogo.
**2** - Usar de modelos no formato *landing/hotsite*, talvez com um novo diretório **/campanhas**.
**3** - Cada página fica a cargo de explorar de uma forma criativa a intenção principal, adoção, abusar de CTAs, novas imagens, cores, etc (apenas não fugindo muito do padrão).
**3a** - Quem sabe com relação a essa variação de cores nas páginas de campanha para dar um destaque maior as ações, criar um novo **campanhas.css** com uma palette de cores que podem ser facilmente usadas nas campanhas.
4 - A publicação dessas campanhas deve ser monitorada com uma url de trackeamento, assim fica mais fácil de saber/mensurar quais as ações chamam mais a atenção do público.

Bom, daqui a pouco devo começar a montas umas páginas de campanhas, breve estarei postando sobre.

Para referência e quem talvez queira entender mais, duas urls do Facebook Developer para ajudar a entender as tags do [Open Graph](https://developers.facebook.com/docs/sharing/webmasters) e [Debugar](https://developers.facebook.com/tools/debug/sharing/) as urls de teste.

See ya ;)

**Comment by cdiegosr** [comment]
Esse campanhas.css seria muito útil mesmo! Assim como as imagens independentes, facilitaria muito a replicação sem muito trabalho

**Comment by fititnt** [comment]
Pessoal, a página está publicada em http://pokemongo.vet.br/aluguel-de-animais.html. Obrigado a todas as pessoas que ajudaram.

## Muito Importante
- [ ] Trocar a imagem que aparece ao compartilhar esta página no Facebook/Twitter. Usar debug em https://developers.facebook.com/tools/debug/. Ideal: Provavelmente uma foto de cães muito felizes levados para passear, tamanho exato 1200x630

## Importante
- [ ] A tabela com os preços não quebra muito feio no Mobile. Hotfixes imediatos e melhorias mais decentes mais tardes são muito bem vindas

## Se alguém tiver como
- [ ] Fazer o botão "adotar" tremer de vez em quando (talvez a cada 13~20 segundos, sem precisar de hover do mouse; (sim, isso chama atenção; sim, é chato, mas converte)
- [ ] Pensar em alguma coisa daquelas toscas mesmo, aonde a pessoa tem apenas 10 minutos para aceitar a venda promocional (adoção). É so pra brincar com as pessoas, como essas páginas exageradas de venda
- [ ] Talvez implementar aqueles popups irritantes de quando a pessoa move o mouse para fora da tela ou quer fechar a janela e dizer "Aproveite nossa promoção AGORA e ganhe (algo)". Isso talvez seja bom só ter o conceito que depois a gente discute

Vale a pena quem for contribuir, ler os comentários que fiz no código fonte para verem as motivações https://github.com/pokemongovet/pokemongo.vet.br/blob/gh-pages/aluguel-de-animais.html#L1

**Comment by blackmoral** [comment]
Boa,
algumas alterações desse issue:
- Implementado um exit popup, o texto não sei se é o ideal, mas é fácil de alterar.

> **Obs.:** É definido um cookie (em dias) que pode ser alterado na variável: ***cookieExp: 0***.

- Botão **Alugar** com uma animação a cada 10s.

Ainda estou pensando em algo para o lance do "tempo acabando", breve mais um commit.

Vou enviar o PR, mas já pode verificar como ficou em:
https://blackmoral.github.io/pokemongo.vet.br/aluguel-de-animais.html

Se virem algum problema só falar.

## Se alguém tiver como
- [x] Fazer o botão "adotar" tremer de vez em quando (talvez a cada 13~20 segundos, sem precisar de hover do mouse; (sim, isso chama atenção; sim, é chato, mas converte)
- [ ]  Pensar em alguma coisa daquelas toscas mesmo, aonde a pessoa tem apenas 10 minutos para aceitar a venda promocional (adoção). É so pra brincar com as pessoas, como essas páginas exageradas de venda
- [x] Talvez implementar aqueles popups irritantes de quando a pessoa move o mouse para fora da tela ou quer fechar a janela e dizer "Aproveite nossa promoção AGORA e ganhe (algo)". Isso talvez seja bom só ter o conceito que depois a gente discute

**Comment by icoffani** [comment]
Concordo com @blackmoral em relação às *clickbaits* explorarem melhor a intenção do projeto. Como Pokémon GO já foi lançado, além de ter a possibilidade de não conseguir "fisgar" as pessoas mascarando o projeto, tem o fator da decepção: quando não deixamos nem uma ideia, mesmo que subliminar, do que o link trata, isso pode gerar um impacto negativo logo de início no usuário. O que vocês acham de eu criar um issue com esse tema mais detalhadamente?

**Comment by blackmoral** [comment]
Boa,
demorou mas chegou, algumas correções do meu PR para esse issue:
- Implementado um novo exit popup, testar novamente se irá bugar alguma coisa, para mim está ok.

> **Obs.:** 
<del>
- É definido um cookie (em dias) que pode ser alterado na variável: ***cookieExp: 0***.
</del>
- Popup desabilitado no responsivo para telas menores que 768px. 

- Botão <del>**Alugar**</del> **Adotar** com uma animação a cada 10s.

 - Implementado o texto "Só restam:10m:00s!" no pacote promocional, não existe nenhuma ação, é apenas para chamar a atenção, como foi comentado.

> **Obs.:** 
- Meu arquivo .js foi movido para a pasta **assets/js/plugins**.
- Removido os .js das funções desse issue ***(exitpopup.js, jshake.js)*** e foi tudo implementado em um único arquivo, **pokepoodle.js**.

O PR já está feito porém não sei se meu commit já altera ele, ainda não tinha feito isso antes, mas já pode verificar como ficou em:
https://blackmoral.github.io/pokemongo.vet.br/aluguel-de-animais.html

Se virem algum problema só falar.

## Se alguém tiver como
- [x] Fazer o botão "adotar" tremer de vez em quando (talvez a cada 13~20 segundos, sem precisar de hover do mouse; (sim, isso chama atenção; sim, é chato, mas converte)
- [x]  Pensar em alguma coisa daquelas toscas mesmo, aonde a pessoa tem apenas 10 minutos para aceitar a venda promocional (adoção). É so pra brincar com as pessoas, como essas páginas exageradas de venda
- [x] Talvez implementar aqueles popups irritantes de quando a pessoa move o mouse para fora da tela ou quer fechar a janela e dizer "Aproveite nossa promoção AGORA e ganhe (algo)". Isso talvez seja bom só ter o conceito que depois a gente discute

**Comment by blackmoral** [comment]
@icoffani, concordo com a discussão desse tema, acho que será importante, suas considerações foram muito válidas.

Dentro desse contexto, sugiro na verdade manter o foco do projeto ainda no jogo, porém como uma ferramenta de **integração** a causa, como por exemplo ações que incentivem o dog walker voluntário enquanto captura/caça pokémons, incentivos como por exemplo a cada X pokémons capturados doe X para tal abrigo, esse tipo de ação para tirar proveito dos jogadores que tenham interesse em ajudar.

Acho válido também focar em ações que incentivem ainda as pessoas que por algum motivo não podem ter animais de estimação mas que gostem deles, queiram ajudar, talvez com donativos, passeios semanais, auxílio para cuidar dos cães algumas vezes no mês, sei lá, coisas boas para as instituições e que possam integrar quem pode de alguma forma ajudar os animais, mesmo que não os levando para casa.

See ya ;)

**Comment by fititnt** [comment]
Nossa @blackmoral ficou massa isso, voce ate colocou pra ver ao vivo.

Uma pergunta, voce não quer, também, acessar o nosso chat? ele fica em https://pgovet.rocket.chat/channel/site-principal.

da forma como voce está contribuindo, pode ser interessante pra todo mundo voce pelo menos por um tempo ter poder de escrita direto no branch principal. Creio que a @rcgivisiez e a @icoffani concordariam com isso.

**Comment by blackmoral** [comment]
Que bom que gostou, eu não tenho muita prática no git/github (esse é o primeiro projeto que participo), tenho certo receio de cometer algum erro tendo escrita master, mas podemos ver isso sim.

Com certeza entrarei no chat, vai ser mais prático pra trocar ideias.
