### ISSUE TITLE
Link no menu para casosdesucesso.pokemongo.vet.br

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/pokemongo.vet.br#60]
O outro repositório aqui da organização está no ar em http://casosdesucesso.pokemongo.vet.br/. Parabéns aos envolvidos!

Quem pode por o link para "http://casosdesucesso.pokemongo.vet.br/" com texto "Casos de Sucesso" no menu antes de "Sobre"?

Após fazermos isso, talvez seja interessante por na URL as UTM para ficar mais claro pro Google Analytics de onde veio a visita.

**Comment by fititnt** [comment]
@evansantos ou @blackmoral , se estiverem perto do computador pra fazer isso hj, dão um aviso aqui.

**Comment by blackmoral** [comment]
Tá beleza, pode deixar comigo. O tracker no caso vai só no Casos de Sucesso?

**Comment by fititnt** [comment]
Não não. As tags UTM são parametros adicionais que a gente coloca numa URL, para que o site de destino saiba quem enviou, qual campanha enviou, qual tipo de mídia (banner? link de texto? click de e-mail?)

Isso acaba tendo que fazer a gente pensar como fazer isso, pois é algo que aparece na interface do Google Analytics do site de destino.

https://support.google.com/analytics/answer/1033867?hl=pt-BR

**Comment by blackmoral** [comment]
É, eu viajei aqui, li errado kkk
Daqui a pouco to comitando.

**Comment by fititnt** [comment]
Pronto. Acho que a gente pode começar com esse tipo de link aqui. Podemos melhorar mais tarde, mas já é um inicio.

http://casosdesucesso.pokemongo.vet.br/?utm_source=pokemongovet&utm_medium=link-texto&utm_content=menu-principal&utm_campaign=sites-grupo-pokemongovet

**Comment by blackmoral** [comment]
Concluído. ;)
