### ISSUE TITLE
Propor projeto em github.com/camilatigre/listamaravilhosaopensource

### ISSUE THREAD

**Issue by fititnt** [pokemongovet/pokemongo.vet.br#62]
Alguém pode propor o https://github.com/pokemongovet/pokemongo.vet.br em https://github.com/camilatigre/listamaravilhosaopensource marcado como "iniciante" e linguanges "HTML,CSS" ?

**Comment by anabastos** [comment]
https://github.com/camilatigre/listamaravilhosaopensource/pull/22

**Comment by blackmoral** [comment]
O PR já foi aceito no https://github.com/camilatigre/listamaravilhosaopensource, obrigado @anabastos pela inclusão.
