### ISSUE TITLE
Canvas HTML5 para montagens com imagens

### ISSUE THREAD

**Issue by rcgivisiez** [pokemongovet/pokemongo.vet.br#7]
Precisamos de ajuda!

Temos algumas das ideias que envolvem fazer montagem de imagens, que hoje podem ser feitas com softwares como Gimp ou Photoshop, mas isso “não escala”.

O ideal é que a implementação desse tipo de ideia funcione via navegador, não necessariamente via celular, mas no mínimo no desktop.
	
### Exemplos práticos:
- Montagens de “quem é esse pokémon?” onde a foto interna é de um animal para adoção;
- Foto de animal para adoção com camada de texto, bordas estilizadas, ou até mesmo filtro.

### Público-alvo:
- Assessoria de imprensa de centro de zoonoses;
- ONGs de proteção a animais;
- Protetores de animais em geral.

### Nível de habilidade para o usuário final:
- Inviável pedir que imagens enviadas tenham exatamente uma largura e altura;
- Não é garantido que o tamanho do arquivo vai ter limites mínimos ou máximos (pode aparecer foto de 13MB tirada direto de uma câmera de celular);
- Interface preferencialmente simples (ex.: botão verde enorme para fazer download, e não “clique com botão direito para salvar arquivo”).

O pessoal pode usar o espaço aqui para indicar bibliotecas ou técnicas pra a execução disso. A partir das possibilidades reais de implementação dadas por vocês, nossa iniciativa poderá tirar conclusões de ações práticas.

**Comment by uselessdev** [comment]
Boa noite, há alguns meses precisei de uma solução semelhante, a principio optei por usar uma biblioteca pronta, depois de pesquisar algumas acabei utilizando o [fabricjs](https://github.com/kangax/fabric.js/) pela simplicidade, infelizmente devido ao prazo apertado acabamos decidindo pegar uma coisa pronta e adaptar, infelizmente não guardei o que já tinha desenvolvido :disappointed:  .

**Comment by cassianorsilva** [comment]
Talvez, para trabalhar as imagens, poderia ser utilizado a biblioteca: [node-imagemagick-native](https://github.com/elad/node-imagemagick-native) antes de colocar no canvas.

**Comment by tofanelli** [comment]
algo assim?

https://pixlr.com/editor/
https://www.sumopaint.com/home/

**Comment by fititnt** [comment]
No momento, é pra ser algo um pouco mais simples. Está mais para algo como "memegenerator" (imagens padrões, textos que mudam) ou "twibbon" (foto muda, mas uma camada é aplicada) do que um editor completo, estilo Paint ou Photoshop.

No momento atual, a iniciativa tem apenas uma landing page estática. Provavelmente isso não deve mudar tão cedo, ate pra estimular ajuda de programadores. O ponto é que, por uma estratégia de divulgação, as coordenadoras @icoffani e @rcgivisiez estão considerando ver meios de quem sabe ir um pouco mais alem, mas não vale muito a pena fazer algo muito complexo sem antes ver se tem interesse do publico final.

Isso é menos sobre "quão bonito é o código" e mais sobre "algo que funciona" mesmo se a gente tiver que usar uma API ou um serviço de terceiro. Isso pode melhorar mais tarde, mas se pra muito em breve, tipo antes do dia 31 de Julho, já tivermos algo minimamente funcional, se algum jornal for divulgar a ideia, a gente já tem algo pronto

**Comment by fititnt** [comment]
**Vou dar um exemplo. Não quer dizer que é isso que seria a melhor opção, mas é um exemplo.**

Abaixo é uma imagem muito comum relacionada a Pokemons. Se o pessoal do marketing achar que tem apelo permitir que ongs usem um "pokemon-animal-para-adocao-generator" seja uma boa ideia, o resultado final poderia ser um usuário enviar uma foto qualquer, e isso ficar atrás de uma imagem como essa aqui.

![who-is-that-pokemon](https://cloud.githubusercontent.com/assets/812299/17237148/20526f66-5525-11e6-8415-e1ac0d856742.jpg)


Muito provavelmente é mais sobre apenas mesclar texto em uma imagem, ou mesclar imagens e permitir download.

**Comment by icoffani** [comment]
Oi programadores! **MUITO** obrigada pela colaboração de vocês.

O nosso público-alvo tende a gostar de vídeos e gifs. Uma das nossas idéias seria permitir montagens que façam um animal resgatado e disponível para adoção se pareça mais com um pokémon, entendem?

Por exemplo: quando a pessoa faz upload de uma foto, ela pode arrastar um chapéuzinho do Pikachu, ou então uma roupinha do Charmander e, quem sabe colocar algum texto simples em um local padrão (sem muitas firulas). Depois disso ela pode baixar essa imagem customizada e divulgar na própria página.

Pra terem ideia do nosso tipo de público, dêem uma olhada em https://www.facebook.com/PokemonGoVet/. Queremos cativar principalmente pessoas entre 16 a 28 anos, na sua maioria mulheres (mesmo que o público masculino não esteja excluído, pelo o que notamos, as mulheres se interessaram mais até agora) e muitas dessas pessoas gostam de imagens e vídeos meigos. Isso pode parecer algo infantil, mas a intenção é justamente trazer pra primeira adoção gente que gosta disso.

**Comment by uselessdev** [comment]
@fititnt, @icoffani  Deu pra entender bem a ideia. 

Na minha situação, acabei usando [esse](https://codecanyon.net/item/pixie-image-editor/10721475) mas sinceramente não sei se é 'aplicável' ao que vocês precisam.

**Comment by lbotinelly** [comment]
Sugestão de processo de implementação:

Utilize uma lib para extrair o contexto de imagem (a parte que importa) do fundo. Existem soluções tanto pagas quanto gratuitas para isso. 

Exemplo a seguir:

- Imagem raw:  
![03_cao_centado](https://cloud.githubusercontent.com/assets/6088476/17252357/6ea35694-557a-11e6-9b70-24705e3ec75e.jpg)  
(URL original: http://animais.culturamix.com/blog/wp-content/gallery/adocao-de-caes-em-sao-paulo1/03_cao_centado.jpg)

- Extração de contexto:  
![2016-07-29 10_41_50-instantly remove image backgrounds online - clipping magic](https://cloud.githubusercontent.com/assets/6088476/17252419/ae4715ba-557a-11e6-8924-8faa2d810fb2.png)

O conteúdo a seguir pode ser implementado tanto como solução client- como server-side. 

- De posse da imagem com canal alfa, extraia o canal e inverta:  
![untitled3](https://cloud.githubusercontent.com/assets/6088476/17252869/4e6b0550-557c-11e6-8b8e-44f682179199.png)

- Aplique sobre o fundo 'Quem é esse Pokémon?':  
![untitled](https://cloud.githubusercontent.com/assets/6088476/17252885/602c19d2-557c-11e6-88df-24c339383805.png)

- Finalmente, revele a imagem original:  
![untitled2](https://cloud.githubusercontent.com/assets/6088476/17252912/7b3f7462-557c-11e6-9e2d-8cb5c92e85f2.png)

**Comment by tawsbob** [comment]
Posso ajudar!

Precisamos de uma API para cadastrar o bicho e exibir em algum lugar correto?
ou só o gerador de imagens?

**Comment by fititnt** [comment]
Opa @tawsbob, creio que é mais pra gerar imagens mesmo.

É muito provável que a forma de crescer mais rápido é permitir que as pessoas possam pegar, criar a imagem, baixar ela, e dai usar como referência na hora de divulgar um novo animal pra adoção.

Claro que pode valer a pena ter URL pra compartilhamento, mas não sei se vale a pena fazer isso sem antes ver se as pessoas começam a usar o modo  mais simples.

A não ser que já exista uma solução pronta, como fazer um fork de algum memegenerator open source, creio que é melhor primeiro só fazer funcionar.

**Comment by icoffani** [comment]
Achei um [vídeo] (https://www.facebook.com/crusoedachshund/videos/vb.155275957894241/1208428682578958/?type=2&theater&notif_t=video_reply&notif_id=1470304652715533)  no Facebook que exemplifica bem a ideia do que podemos fazer. No caso, pode ser um cachorro que muda de nome, e tributos (type, weight, height, etc) aleatoriamente. O que seria legal porque as pessoas se interessariam em colocar a foto de cachorro para ver o que daria, tipo aqueles testes que o pessoal adora no Facebook. Ou então uma imagem com o gramado do jogo e a pokebola mesmo. 
Aqui alguns exemplos:
![1](https://cloud.githubusercontent.com/assets/20593469/17398199/f33602c6-5a11-11e6-83de-7ec3e0402920.jpg)
![2](https://cloud.githubusercontent.com/assets/20593469/17398147/b342a03e-5a11-11e6-952e-4b28c83872d4.jpg)

**Comment by rcgivisiez** [comment]
Obrigado a todos pela participação aqui!

Se tivermos pelo menos mais duas pessoas pessoas, creio que vai ser feito em NodeJS. Discussões podem ser feitas também em https://pgovet.rocket.chat/channel/gerador-fotos-adocao

Vamos fechar esse issue e manter toda discussão restante em #50
